FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /app
COPY rosaauth-server /app/rosaauth-server
COPY internal/database/migrations /app/internal/database/migrations
COPY web /app/web

ENTRYPOINT ["/app/rosaauth-server"]
